from __future__ import annotations

from pathlib import Path

APP_NAME = "Gerador de Leitura Bíblica"
APP_VERSION = "1.1.0"
MODEL_NAME = "modelo.pptx"
APP_AUTHOR = "Igreja Tabernáculo do Senhor - Barra do Garças"

OUTPUT_DIR_DEFAULT = Path.home() / "Documents" / "LeituraBiblica"

TEMPLATE_TITLE_INDEX = 1
TEMPLATE_PASTOR_INDEX = 2
TEMPLATE_IGREJA_INDEX = 3
TEMPLATE_FINAL_INDEX = 4

PP_ALIGN_JUSTIFY = 4
PP_SAVE_AS_OPENXML = 24

PLACEHOLDER_LIVRO_CAP = "{livro_cap}"
PLACEHOLDER_TITULO = "{titulo}"
PLACEHOLDER_VERSICULO = "{versiculo}"

PLACEHOLDERS_LIVRO_CAP = (PLACEHOLDER_LIVRO_CAP, "livro cap", "livro_cap")
PLACEHOLDERS_TITULO = (PLACEHOLDER_TITULO, "titulo", "título")
PLACEHOLDERS_VERSICULO = (
    PLACEHOLDER_VERSICULO,
    "versiculo",
    "versículo",
    "versImpar",
    "versPar",
    "versLast",
    "1 - versImpar",
    "2 - versPar",
    "3 - versLast",
    "1 – versImpar",
    "2 – versPar",
    "3 – versLast",
)

BG_APP = "#0a0e1a"
BG_CARD = "#111827"
BG_CARD_INNER = "#0d1520"
BG_TILE = "#162033"
BG_INPUT = "#0f1a2e"

GRAD_START = "#60a5fa"
GRAD_MID = "#3b82f6"

CARD_BORDER = "#1d2d4a"
INPUT_BORDER = "#1d2d4a"
INPUT_BORDER_FOC = "#3b82f6"

FG_TITLE = "#eaf0ff"
FG_LABEL = "#7f9ab3"
FG_INPUT = "#d9eaff"
FG_HINT = "#5a7a9a"
FG_SUCCESS = "#34d399"
FG_ERROR = "#f87171"

FONT_FAMILY = "Segoe UI"
RADIUS = 22
RADIUS_TILE = 18
RADIUS_PILL = 20

# Animation timing tokens (milliseconds)
ANIM_FAST = 140
ANIM_NORMAL = 220
ANIM_SLOW = 350
ANIM_XS = 80
ANIM_FPS = 60
ANIM_FRAME_MS = 16

ANIM_FADE_IN = 260
ANIM_ENTRANCE = 260
ANIM_WINDOW_PULSE = 300
ANIM_STATUS = 200
ANIM_PROGRESS_ENTRANCE = 300
ANIM_ELEVATION_PULSE = 400
ANIM_CARD_DIM = 300
ANIM_CARD_UNDIM = 400
ANIM_PRESS_RESTORE = 180
ANIM_REVEAL_OUT_MULTIPLIER = 2

ANIM_DELAY_CORNERS = 60
ANIM_DELAY_WIRE = 10
ANIM_DELAY_SCALE = 60
ANIM_DELAY_CLIPBOARD = 250

ANIM_STARTUP_MIN_VISIBLE = 500
ANIM_STARTUP_POLL = 80
ANIM_ENTRANCE_DELAYS = (0, 50, 110, 190, 240, 290)

ICON_BOOK = "📖"
ICON_PLAY = "▶"
ICON_CHECK = "✓"
ICON_CROSS = "✗"
ICON_FOLDER = "📂"
